"""Authoritative typed contracts for KERASCAN Week 1.

The Pydantic models in this module are the source of truth for the JSON
schemas under ``schemas/``.  The JSON files are generated by
``scripts/generate_schemas.py``.
"""

from __future__ import annotations

import json
from datetime import datetime
from enum import Enum
from typing import Any
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, field_validator

SCREENING_DISCLAIMER = (
    "Screening/referral support only; not a diagnosis. Pentacam and clinician "
    "review are required for confirmation."
)
_AWARE_DATETIME_JSON_SCHEMA = {
    "description": "RFC 3339 date-time with an explicit timezone offset.",
    "pattern": r".*(?:Z|[+-][0-9]{2}:[0-9]{2})$",
}


class ContractModel(BaseModel):
    """Shared strict settings for all persisted and API-facing contracts."""

    model_config = ConfigDict(
        extra="forbid",
        frozen=True,
        str_strip_whitespace=True,
        allow_inf_nan=False,
    )


class Eye(str, Enum):
    OD = "OD"
    OS = "OS"


class AnalysisMode(str, Enum):
    MOCK = "MOCK"


class ResultStatus(str, Enum):
    RECAPTURE_REQUIRED = "RECAPTURE_REQUIRED"
    MANUAL_REVIEW = "MANUAL_REVIEW"
    PENTACAM_EVALUATION_RECOMMENDED = "PENTACAM_EVALUATION_RECOMMENDED"
    SCREEN_NEGATIVE = "SCREEN_NEGATIVE"
    BLOCKED = "BLOCKED"


class ReasonCode(str, Enum):
    MOCK_MODE = "MOCK_MODE"
    ANALYSIS_NOT_PERFORMED = "ANALYSIS_NOT_PERFORMED"
    CALIBRATION_UNVALIDATED = "CALIBRATION_UNVALIDATED"
    CALIBRATION_MISSING = "CALIBRATION_MISSING"
    CALIBRATION_INVALID = "CALIBRATION_INVALID"
    DEVICE_UNKNOWN = "DEVICE_UNKNOWN"
    DEVICE_CONFIGURATION_MISMATCH = "DEVICE_CONFIGURATION_MISMATCH"
    IMAGE_EMPTY = "IMAGE_EMPTY"
    IMAGE_CORRUPT = "IMAGE_CORRUPT"
    IMAGE_UNSUPPORTED_FORMAT = "IMAGE_UNSUPPORTED_FORMAT"
    IMAGE_EXTENSION_CONTENT_MISMATCH = "IMAGE_EXTENSION_CONTENT_MISMATCH"
    IMAGE_TOO_LARGE = "IMAGE_TOO_LARGE"
    IMAGE_DIMENSIONS_EXCEEDED = "IMAGE_DIMENSIONS_EXCEEDED"
    IMAGE_READ_ERROR = "IMAGE_READ_ERROR"
    INVALID_METADATA = "INVALID_METADATA"
    CLINICAL_OUTPUT_BLOCKED = "CLINICAL_OUTPUT_BLOCKED"
    STAGE_NOT_IMPLEMENTED = "STAGE_NOT_IMPLEMENTED"


class StageName(str, Enum):
    INPUT_VALIDATION = "INPUT_VALIDATION"
    DEVICE_CONFIGURATION_VALIDATION = "DEVICE_CONFIGURATION_VALIDATION"
    IMAGE_LOADING = "IMAGE_LOADING"
    CALIBRATION_VALIDATION = "CALIBRATION_VALIDATION"
    QUALITY_ASSESSMENT = "QUALITY_ASSESSMENT"
    CENTRE_DETECTION = "CENTRE_DETECTION"
    SEGMENTATION = "SEGMENTATION"
    RING_TRACKING = "RING_TRACKING"
    FEATURE_EXTRACTION = "FEATURE_EXTRACTION"
    OUTCOME_POLICY = "OUTCOME_POLICY"


class StageState(str, Enum):
    NOT_RUN = "NOT_RUN"
    PASSED = "PASSED"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"


class CalibrationStatus(str, Enum):
    MISSING = "MISSING"
    INVALID = "INVALID"
    UNVALIDATED = "UNVALIDATED"
    VALIDATED = "VALIDATED"


class ImageFormat(str, Enum):
    JPEG = "JPEG"
    PNG = "PNG"


class QualityStatus(str, Enum):
    NOT_ASSESSED = "NOT_ASSESSED"
    MEASURED = "MEASURED"
    INVALID = "INVALID"


class CentreStatus(str, Enum):
    NOT_DETECTED = "NOT_DETECTED"
    DETECTED = "DETECTED"


class RingTrackingStatus(str, Enum):
    NOT_RUN = "NOT_RUN"
    TRACKED = "TRACKED"


class FeatureStatus(str, Enum):
    NOT_RUN = "NOT_RUN"
    EXTRACTED = "EXTRACTED"


class MeasurementValidity(str, Enum):
    MEASURED = "MEASURED"
    UNAVAILABLE = "UNAVAILABLE"


def _require_timezone(value: datetime | None) -> datetime | None:
    if value is None:
        return None
    if value.tzinfo is None or value.utcoffset() is None:
        raise ValueError("timestamp must include a timezone offset")
    return value


class AnalysisRequest(ContractModel):
    """Metadata submitted with one original capture image."""

    schema_version: str = Field(default="1.0.0", min_length=1, max_length=32)
    anonymous_patient_id: str = Field(min_length=1, max_length=128)
    eye: Eye
    capture_session_id: str = Field(min_length=1, max_length=128)
    device_version: str = Field(min_length=1, max_length=128)
    operator_id: str = Field(min_length=1, max_length=128)
    capture_timestamp: datetime = Field(json_schema_extra=_AWARE_DATETIME_JSON_SCHEMA)
    analysis_mode: AnalysisMode = AnalysisMode.MOCK

    _capture_timestamp_timezone = field_validator("capture_timestamp")(
        _require_timezone
    )


class RuntimeLimits(ContractModel):
    """Limits applied before an image is decoded or processed."""

    max_upload_bytes: int = Field(gt=0)
    max_decoded_width_px: int = Field(gt=0)
    max_decoded_height_px: int = Field(gt=0)
    max_decoded_pixels: int = Field(gt=0)
    supported_extensions: list[str] = Field(min_length=1)

    @field_validator("supported_extensions")
    @classmethod
    def _normalise_extensions(cls, value: list[str]) -> list[str]:
        normalised = [extension.strip().lower() for extension in value]
        if any(not extension.startswith(".") for extension in normalised):
            raise ValueError("supported extensions must start with '.'")
        if len(set(normalised)) != len(normalised):
            raise ValueError("supported extensions must be unique")
        return normalised


class StorageConfiguration(ContractModel):
    retain_uploaded_images: bool = False
    artifact_directory: str = Field(min_length=1)
    temporary_directory: str | None = None


class PhoneCameraIdentity(ContractModel):
    phone_manufacturer: str | None = None
    phone_model: str | None = None
    camera_module: str | None = None
    lens_identity: str | None = None


class CaptureSpecification(ContractModel):
    resolution_width_px: int | None = Field(default=None, gt=0)
    resolution_height_px: int | None = Field(default=None, gt=0)
    image_format: str | None = None
    iso: int | None = Field(default=None, gt=0)
    exposure_time_us: int | None = Field(default=None, gt=0)
    focus_mode: str | None = None
    flash_mode: str | None = None
    zoom_factor: float | None = Field(default=None, gt=0)


class PlacidoSpecification(ContractModel):
    ring_count: int | None = Field(default=None, gt=0)
    ring_diameters_mm: list[float] | None = None
    ring_thickness_mm: float | None = Field(default=None, gt=0)
    ring_spacing_mm: list[float] | None = None


class GeometrySpecification(ContractModel):
    phone_to_device_geometry: str | None = None
    camera_to_attachment_offset_mm: float | None = Field(default=None, ge=0)
    working_distance_mm: float | None = Field(default=None, gt=0)
    orientation_convention: str | None = None


class PhysicalDeviceSpecification(ContractModel):
    phone_camera: PhoneCameraIdentity
    capture: CaptureSpecification
    placido: PlacidoSpecification
    geometry: GeometrySpecification


class DeviceConfiguration(ContractModel):
    """Versioned device definition and its non-clinical runtime limits."""

    device_version: str = Field(min_length=1, max_length=128)
    display_name: str = Field(min_length=1, max_length=256)
    physical: PhysicalDeviceSpecification
    runtime_limits: RuntimeLimits
    storage: StorageConfiguration
    calibration_package_path: str | None = None

    def calibration_fingerprint_payload(self) -> dict[str, Any]:
        """Return only fields whose change invalidates physical calibration."""

        return self.model_dump(mode="json", include={"device_version", "physical"})


class SafetyConfiguration(ContractModel):
    allow_screen_negative: bool = False


class UiPreferences(ContractModel):
    show_preview: bool = True
    theme: str = "default"


class ApplicationConfiguration(ContractModel):
    software_version: str = Field(min_length=1, max_length=64)
    default_analysis_mode: AnalysisMode = AnalysisMode.MOCK
    host: str = "127.0.0.1"
    port: int = Field(default=8000, gt=0, le=65535)
    max_request_bytes: int = Field(gt=0)
    storage: StorageConfiguration
    safety: SafetyConfiguration
    ui_preferences: UiPreferences
    devices_directory: str = Field(min_length=1)


class CalibrationManifest(ContractModel):
    calibration_identifier: str = Field(min_length=1, max_length=256)
    device_version: str = Field(min_length=1, max_length=128)
    device_configuration_hash: str = Field(pattern=r"^[0-9a-f]{64}$")
    status: CalibrationStatus
    created_at: datetime = Field(json_schema_extra=_AWARE_DATETIME_JSON_SCHEMA)
    source: str | None = None

    _created_at_timezone = field_validator("created_at")(_require_timezone)


class CameraIntrinsicsPackage(ContractModel):
    calibration_identifier: str = Field(min_length=1, max_length=256)
    device_configuration_hash: str = Field(pattern=r"^[0-9a-f]{64}$")
    camera_matrix: list[list[float]] | None = None
    distortion_coefficients: list[float] | None = None


class PlacidoGeometryPackage(ContractModel):
    calibration_identifier: str = Field(min_length=1, max_length=256)
    device_configuration_hash: str = Field(pattern=r"^[0-9a-f]{64}$")
    ring_count: int | None = Field(default=None, gt=0)
    ring_diameters_mm: list[float] | None = None
    working_distance_mm: float | None = Field(default=None, gt=0)


class CalibrationResults(ContractModel):
    calibration_identifier: str = Field(min_length=1, max_length=256)
    device_configuration_hash: str = Field(pattern=r"^[0-9a-f]{64}$")
    status: CalibrationStatus
    validated_at: datetime | None = Field(
        default=None, json_schema_extra=_AWARE_DATETIME_JSON_SCHEMA
    )
    notes: str = ""

    _validated_at_timezone = field_validator("validated_at")(_require_timezone)


class CalibrationValidation(ContractModel):
    status: CalibrationStatus
    calibration_identifier: str | None = None
    device_configuration_hash: str = Field(pattern=r"^[0-9a-f]{64}$")
    compatible: bool
    reason_codes: list[ReasonCode] = Field(default_factory=list)
    message: str


class StageExecution(ContractModel):
    stage_name: StageName
    state: StageState
    started_at: datetime | None = Field(
        default=None, json_schema_extra=_AWARE_DATETIME_JSON_SCHEMA
    )
    finished_at: datetime | None = Field(
        default=None, json_schema_extra=_AWARE_DATETIME_JSON_SCHEMA
    )
    reason_codes: list[ReasonCode] = Field(default_factory=list)
    message: str

    _started_at_timezone = field_validator("started_at")(_require_timezone)
    _finished_at_timezone = field_validator("finished_at")(_require_timezone)


class QualityMeasurements(ContractModel):
    status: QualityStatus = QualityStatus.NOT_ASSESSED
    image_width_px: int | None = Field(default=None, gt=0)
    image_height_px: int | None = Field(default=None, gt=0)
    channel_count: int | None = Field(default=None, gt=0)
    source_format: ImageFormat | None = None
    orientation_transformation: str = "none"
    brightness_mean: float | None = None
    contrast_stddev: float | None = None
    validity: MeasurementValidity = MeasurementValidity.UNAVAILABLE


class Point2D(ContractModel):
    x_px: float
    y_px: float


class CentreInformation(ContractModel):
    status: CentreStatus = CentreStatus.NOT_DETECTED
    x_px: float | None = None
    y_px: float | None = None
    coordinate_system: str = "image_pixels_xy"
    source: str | None = None


class RingTrackingInformation(ContractModel):
    status: RingTrackingStatus = RingTrackingStatus.NOT_RUN
    ring_count: int | None = Field(default=None, gt=0)
    tracked_ring_count: int | None = Field(default=None, gt=0)
    tracked_points: list[Point2D] | None = None
    validity: MeasurementValidity = MeasurementValidity.UNAVAILABLE


class FeatureMeasurements(ContractModel):
    status: FeatureStatus = FeatureStatus.NOT_RUN
    sim_k1_diopters: float | None = None
    sim_k2_diopters: float | None = None
    mean_k_diopters: float | None = None
    astigmatism_diopters: float | None = None
    validity: MeasurementValidity = MeasurementValidity.UNAVAILABLE


class ArtifactReference(ContractModel):
    artifact_type: str = Field(min_length=1, max_length=128)
    uri: str = Field(min_length=1, max_length=1024)
    sha256: str | None = Field(default=None, pattern=r"^[0-9a-f]{64}$")
    retained: bool = False


class AnalysisResult(ContractModel):
    schema_version: str = Field(default="1.0.0", min_length=1, max_length=32)
    software_version: str = Field(min_length=1, max_length=64)
    analysis_id: UUID
    analysis_mode: AnalysisMode
    timestamp: datetime = Field(json_schema_extra=_AWARE_DATETIME_JSON_SCHEMA)
    anonymous_patient_id: str = Field(min_length=1, max_length=128)
    eye: Eye
    capture_session_id: str = Field(min_length=1, max_length=128)
    operator_id: str = Field(min_length=1, max_length=128)
    capture_timestamp: datetime = Field(json_schema_extra=_AWARE_DATETIME_JSON_SCHEMA)
    status: ResultStatus
    reason_codes: list[ReasonCode] = Field(min_length=1)
    message: str = Field(min_length=1)
    stage_execution: list[StageExecution] = Field(min_length=1)
    device_version: str = Field(min_length=1, max_length=128)
    device_configuration_hash: str | None = Field(
        default=None, pattern=r"^[0-9a-f]{64}$"
    )
    calibration_status: CalibrationStatus
    calibration_identifier: str | None = None
    original_image_sha256: str | None = Field(default=None, pattern=r"^[0-9a-f]{64}$")
    quality_measurements: QualityMeasurements
    centre_information: CentreInformation
    ring_tracking: RingTrackingInformation
    features: FeatureMeasurements
    artifact_references: list[ArtifactReference] = Field(default_factory=list)
    screening_disclaimer: str = SCREENING_DISCLAIMER

    _timestamp_timezone = field_validator("timestamp")(_require_timezone)
    _capture_timestamp_timezone = field_validator("capture_timestamp")(
        _require_timezone
    )

    def to_json(self) -> str:
        """Serialize using strict JSON rules; unavailable numbers remain null."""

        return json.dumps(
            self.model_dump(mode="json"),
            ensure_ascii=False,
            allow_nan=False,
            separators=(",", ":"),
        )


class DatasetManifestRow(ContractModel):
    schema_version: str = Field(default="1.0.0", min_length=1, max_length=32)
    row_id: str = Field(min_length=1, max_length=128)
    anonymous_patient_id: str = Field(min_length=1, max_length=128)
    eye: Eye
    capture_session_id: str = Field(min_length=1, max_length=128)
    device_version: str = Field(min_length=1, max_length=128)
    operator_id: str = Field(min_length=1, max_length=128)
    capture_timestamp: datetime = Field(json_schema_extra=_AWARE_DATETIME_JSON_SCHEMA)
    image_path: str = Field(min_length=1, max_length=1024)
    original_image_sha256: str | None = Field(default=None, pattern=r"^[0-9a-f]{64}$")
    analysis_id: UUID | None = None

    _capture_timestamp_timezone = field_validator("capture_timestamp")(
        _require_timezone
    )


class DatasetManifest(ContractModel):
    schema_version: str = Field(default="1.0.0", min_length=1, max_length=32)
    dataset_id: str = Field(min_length=1, max_length=128)
    created_at: datetime = Field(json_schema_extra=_AWARE_DATETIME_JSON_SCHEMA)
    rows: list[DatasetManifestRow] = Field(default_factory=list)

    _created_at_timezone = field_validator("created_at")(_require_timezone)


class DeviceListing(ContractModel):
    device_version: str
    display_name: str
    device_configuration_hash: str = Field(pattern=r"^[0-9a-f]{64}$")
    calibration_status: CalibrationStatus
    calibration_identifier: str | None = None


class DeviceListResponse(ContractModel):
    devices: list[DeviceListing]
